




export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USERS_COMPLETION = 'FETCH_USERS_COMPLETION';
export const FETCH_USERS_COMPLETION_SUCCESS = 'FETCH_USERS_COMPLETION_SUCCESS';
export const FETCH_USERS_COMPLETION_ERROR = 'FETCH_USERS_COMPLETION_ERROR';


export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER';
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS';
export const FETCH_SINGLE_USER_ERROR = 'FETCH_SINGLE_USER_ERROR';